name: Data Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  consume_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Consume data from Coinpaprika API
        run: |
          python src/consume_data.py

      - name: Upload merged data as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: merged-data
          path: data/btc_historical_data.csv

      - name: Preprocess data
        run: |
          python src/preprocess_data.py

      - name: Upload preprocessed data as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-data
          path: data/preprocessed_data.csv
          
      - name: Upload last date as artifact
        uses: actions/upload-artifact@v4
        with:
          name: last-date
          path: data/last_date.txt

  train_and_predict:
    runs-on: ubuntu-latest
    needs: consume_data
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download preprocessed data artifact
        uses: actions/download-artifact@v4
        with:
          name: preprocessed-data
          path: data/

      - name: Download last date artifact
        uses: actions/download-artifact@v4
        with:
          name: last-date
          path: data/

      - name: Train model and save predictions
        run: |
          python src/train_and_predict.py

      - name: Upload predictions as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: predictions
          path: data/combined_predictions.csv

      - name: Upload predictions.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: future-predictions
          path: data/predictions.txt

      - name: Upload model as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: | 
                src/model.json
                src/scaler_X.pkl
                src/scaler_Y.pkl

      - name: Upload evaluation metrics as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: evaluation
          path: data/evaluation_metrics.csv

  commit_and_push:
    runs-on: ubuntu-latest
    needs: train_and_predict
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Download merged data artifact
        uses: actions/download-artifact@v4
        with:
          name: merged-data
          path: data/

      - name: Download preprocessed data artifact
        uses: actions/download-artifact@v4
        with:
          name: preprocessed-data
          path: data/

      - name: Download last date artifact
        uses: actions/download-artifact@v4
        with:
          name: last-date
          path: data/

      - name: Download predictions artifact
        uses: actions/download-artifact@v4
        with:
          name: predictions
          path: data/

      - name: Download future predictions artifact
        uses: actions/download-artifact@v4
        with:
          name: future-predictions
          path: data/

      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: model
          path: src/

      - name: Download evaluation metrics artifacts
        uses: actions/download-artifact@v4
        with:
          name: evaluation
          path: data/

      - name: Commit and push all changes
        env:
          PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add src/model.json src/scaler_X.pkl src/scaler_Y.pkl
          git add data/btc_historical_data.csv data/preprocessed_data.csv data/combined_predictions.csv data/last_date.txt data/evaluation_metrics.csv data/predictions.txt
          git status
          git commit -m "Update data, model, and predictions"
          git push https://x-access-token:${PAT}@github.com/rey-dal/bitcoin.git main